import random
a = random.randint(1, 10)
b = random.randint(1, 10)
c = random.randint(1, 10)
d = random.randint(1, 10)
e = random.randint(1, 10)
tupla = (a,b,c,d,e)
ordem = sorted(tupla)
print (f'os numeros foram {tupla}')
print(f'o menor numero foi {ordem[0]}')
print(f'o maior numero foi {ordem[-1]}')
